"""
PPW Build Script
================
Builds a self-contained Windows executable with the database URI baked in,
so users never need to configure anything.

Usage (local):
    python build.py

Usage (CI — GitHub Actions injects secrets via environment):
    MONGO_URI=... python build.py

Security note:
  The MONGO_URI lives inside the EXE's bytecode. A determined attacker with
  pyinstxtractor could extract it — but that only gives DB access, NOT passwords.
  Every password is AES-256-GCM encrypted with the user's master key which is
  never stored anywhere. MongoDB Atlas IP allowlisting adds a second layer.
"""

import os
import sys
import subprocess
import textwrap
from pathlib import Path

ROOT   = Path(__file__).parent
DIST   = ROOT / "dist"
BUILD  = ROOT / "build_tmp"
SPEC   = ROOT / "ppw.spec"
BUNDLE = ROOT / "_bundled_config.py"
ICON   = ROOT / "extension" / "icons" / "icon.ico"   # optional


def get_secret(name: str) -> str:
    """Read from env var first, then fall back to .env file."""
    val = os.environ.get(name, "")
    if not val:
        env_path = ROOT / ".env"
        if env_path.exists():
            for line in env_path.read_text().splitlines():
                line = line.strip()
                if line.startswith("#") or "=" not in line:
                    continue
                k, _, v = line.partition("=")
                if k.strip() == name:
                    val = v.strip()
                    break
    return val


MONGO_URI     = get_secret("MONGO_URI")
DATABASE_NAME = get_secret("DATABASE_NAME") or "password_manager"

if not MONGO_URI:
    sys.exit("ERROR: MONGO_URI is not set. Add it to .env or export it as an env var.")


def write_bundle():
    BUNDLE.write_text(textwrap.dedent(f"""\
        # AUTO-GENERATED by build.py — DO NOT COMMIT — deleted after build
        MONGO_URI     = {MONGO_URI!r}
        DATABASE_NAME = {DATABASE_NAME!r}
    """))
    print("✓  _bundled_config.py written")


def delete_bundle():
    if BUNDLE.exists():
        BUNDLE.unlink()
        print("✓  _bundled_config.py deleted")


def write_spec():
    icon_arg = f"'{ICON}'" if ICON.exists() else "None"
    SPEC.write_text(textwrap.dedent(f"""\
        # -*- mode: python ; coding: utf-8 -*-
        block_cipher = None

        a = Analysis(
            ['main.py'],
            pathex=[],
            binaries=[],
            datas=[],
            hiddenimports=[
                '_bundled_config',
                'pymongo', 'pymongo.srv', 'pymongo.monitoring',
                'dns.resolver',
                'cryptography',
                'cryptography.hazmat.primitives.ciphers.aead',
                'PyQt6', 'PyQt6.QtWidgets', 'PyQt6.QtCore', 'PyQt6.QtGui',
                'pyperclip',
                'dotenv',
            ],
            hookspath=[],
            runtime_hooks=[],
            excludes=['tkinter', 'matplotlib', 'numpy', 'scipy'],
            cipher=block_cipher,
            noarchive=False,
        )

        pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

        exe = EXE(
            pyz, a.scripts, a.binaries, a.zipfiles, a.datas, [],
            name='PPW-PasswordManager',
            debug=False,
            strip=False,
            upx=True,
            console=False,
            icon={icon_arg},
        )
    """))
    print("✓  ppw.spec written")


def build():
    print("\n── Installing PyInstaller ──")
    subprocess.check_call([sys.executable, "-m", "pip", "install",
                           "pyinstaller>=6.0", "-q"])

    print("\n── Running PyInstaller ──")
    subprocess.check_call([
        sys.executable, "-m", "PyInstaller",
        "--clean",
        "--distpath", str(DIST),
        "--workpath", str(BUILD),
        str(SPEC),
    ])

    exe = DIST / "PPW-PasswordManager.exe"
    if not exe.exists():
        exe = DIST / "PPW-PasswordManager"
    if exe.exists():
        print(f"\n✅  {exe}  ({exe.stat().st_size / 1_048_576:.1f} MB)")
    else:
        print("\n⚠️  EXE not found — check PyInstaller output above.")


if __name__ == "__main__":
    try:
        write_bundle()
        write_spec()
        build()
    finally:
        delete_bundle()
