"""
PPW build script.
Strategy: write a runtime hook (pyi_rth_ppw.py) that sets MONGO_URI as an
environment variable before any app code runs. This is 100% reliable in
PyInstaller - runtime hooks are always executed first in the frozen EXE.

Produces: dist/PPW-PasswordManager.exe  (via PyInstaller)
          dist/PPW-Setup.exe             (via Inno Setup)
"""
import os
import sys
import subprocess
from pathlib import Path

ROOT   = Path(__file__).parent
DIST   = ROOT / "dist"
BUILD  = ROOT / "build_tmp"
SPEC   = ROOT / "ppw.spec"
HOOK   = ROOT / "pyi_rth_ppw.py"   # runtime hook — bundled and run first
ISS    = ROOT / "installer.iss"

ISCC_PATHS = [
    r"C:\Program Files (x86)\Inno Setup 6\ISCC.exe",
    r"C:\Program Files\Inno Setup 6\ISCC.exe",
    r"C:\Program Files (x86)\Inno Setup 5\ISCC.exe",
]


def get_secret(name):
    val = os.environ.get(name, "")
    if not val:
        env_path = ROOT / ".env"
        if env_path.exists():
            for line in env_path.read_text(encoding="utf-8").splitlines():
                line = line.strip()
                if line.startswith("#") or "=" not in line:
                    continue
                k, _, v = line.partition("=")
                if k.strip() == name:
                    val = v.strip()
                    break
    return val


MONGO_URI     = get_secret("MONGO_URI")
DATABASE_NAME = get_secret("DATABASE_NAME") or "password_manager"

if not MONGO_URI:
    sys.exit("ERROR: MONGO_URI is not set.")


def write_runtime_hook():
    """
    Write pyi_rth_ppw.py — a PyInstaller runtime hook.
    Runtime hooks run before ANYTHING else inside the frozen EXE.
    This sets MONGO_URI as an env var so config.py's os.getenv() finds it.
    """
    content = (
        "# PPW runtime hook - sets secrets as env vars before app starts\n"
        "# AUTO-GENERATED by build.py - DO NOT COMMIT\n"
        "import os\n"
        "os.environ.setdefault('MONGO_URI', " + repr(MONGO_URI) + ")\n"
        "os.environ.setdefault('DATABASE_NAME', " + repr(DATABASE_NAME) + ")\n"
    )
    HOOK.write_text(content, encoding="utf-8")
    print("[OK] pyi_rth_ppw.py (runtime hook) written")


def delete_runtime_hook():
    if HOOK.exists():
        HOOK.unlink()
    print("[OK] pyi_rth_ppw.py deleted")


def write_spec():
    spec_text = (
        "block_cipher = None\n"
        "a = Analysis(\n"
        "    ['main.py'],\n"
        "    pathex=[],\n"
        "    binaries=[],\n"
        "    datas=[],\n"
        "    hiddenimports=[\n"
        "        'pymongo', 'pymongo.monitoring',\n"
        "        'dns', 'dns.resolver',\n"
        "        'cryptography',\n"
        "        'cryptography.hazmat.primitives.ciphers.aead',\n"
        "        'PyQt6', 'PyQt6.QtWidgets', 'PyQt6.QtCore', 'PyQt6.QtGui',\n"
        "        'pyperclip', 'dotenv',\n"
        "    ],\n"
        "    hookspath=[],\n"
        "    runtime_hooks=['pyi_rth_ppw.py'],\n"
        "    excludes=['tkinter', 'matplotlib', 'numpy', 'scipy'],\n"
        "    cipher=block_cipher,\n"
        "    noarchive=False,\n"
        ")\n"
        "pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)\n"
        "exe = EXE(\n"
        "    pyz, a.scripts, a.binaries, a.zipfiles, a.datas, [],\n"
        "    name='PPW-PasswordManager',\n"
        "    debug=False, strip=False, upx=True, console=False,\n"
        "    icon=None,\n"
        ")\n"
    )
    SPEC.write_text(spec_text, encoding="utf-8")
    print("[OK] ppw.spec written")


def build_exe():
    print("-- Installing PyInstaller --")
    subprocess.check_call(
        [sys.executable, "-m", "pip", "install", "pyinstaller>=6.0", "-q"]
    )
    print("-- Running PyInstaller --")
    subprocess.check_call([
        sys.executable, "-m", "PyInstaller",
        "--clean",
        "--distpath", str(DIST),
        "--workpath", str(BUILD),
        str(SPEC),
    ])
    exe = DIST / "PPW-PasswordManager.exe"
    if not exe.exists():
        sys.exit("[ERROR] EXE not found after PyInstaller")
    mb = round(exe.stat().st_size / 1_048_576, 1)
    print("[OK] EXE: " + str(exe) + " (" + str(mb) + " MB)")


def find_iscc():
    for path in ISCC_PATHS:
        if Path(path).exists():
            return path
    return None


def build_installer():
    iscc = find_iscc()
    if iscc is None:
        print("-- Inno Setup not found, installing via choco --")
        subprocess.check_call(
            ["choco", "install", "innosetup", "--yes", "--no-progress"],
            stdout=subprocess.DEVNULL,
        )
        iscc = find_iscc()

    if iscc is None:
        sys.exit("[ERROR] Inno Setup not found even after choco install")

    print("-- Running Inno Setup --")
    subprocess.check_call([iscc, str(ISS)])

    setup = DIST / "PPW-Setup.exe"
    if setup.exists():
        mb = round(setup.stat().st_size / 1_048_576, 1)
        print("[OK] Installer: " + str(setup) + " (" + str(mb) + " MB)")
    else:
        sys.exit("[ERROR] PPW-Setup.exe not found after Inno Setup")


if __name__ == "__main__":
    write_runtime_hook()
    write_spec()
    try:
        build_exe()
        build_installer()
    finally:
        delete_runtime_hook()

