import os
import sys
import subprocess
from pathlib import Path

ROOT   = Path(__file__).parent
DIST   = ROOT / "dist"
BUILD  = ROOT / "build_tmp"
SPEC   = ROOT / "ppw.spec"
BUNDLE = ROOT / "_bundled_config.py"
ICON   = ROOT / "extension" / "icons" / "icon.ico"


def get_secret(name):
    val = os.environ.get(name, "")
    if not val:
        env_path = ROOT / ".env"
        if env_path.exists():
            for line in env_path.read_text(encoding="utf-8").splitlines():
                line = line.strip()
                if line.startswith("#") or "=" not in line:
                    continue
                k, _, v = line.partition("=")
                if k.strip() == name:
                    val = v.strip()
                    break
    return val


MONGO_URI     = get_secret("MONGO_URI")
DATABASE_NAME = get_secret("DATABASE_NAME") or "password_manager"

if not MONGO_URI:
    sys.exit("ERROR: MONGO_URI is not set. Add it to .env or set the env var.")


def write_bundle():
    BUNDLE.write_text(
        "# AUTO-GENERATED by build.py - DO NOT COMMIT - deleted after build\n"
        "MONGO_URI     = " + repr(MONGO_URI) + "\n"
        "DATABASE_NAME = " + repr(DATABASE_NAME) + "\n",
        encoding="utf-8",
    )
    print("[OK] _bundled_config.py written")


def delete_bundle():
    if BUNDLE.exists():
        BUNDLE.unlink()
    print("[OK] _bundled_config.py deleted")


def write_spec():
    icon_arg = "'" + str(ICON) + "'" if ICON.exists() else "None"
    spec_text = (
        "block_cipher = None\n"
        "a = Analysis(\n"
        "    ['main.py'],\n"
        "    pathex=[],\n"
        "    binaries=[],\n"
        "    datas=[],\n"
        "    hiddenimports=[\n"
        "        '_bundled_config',\n"
        "        'pymongo', 'pymongo.srv', 'pymongo.monitoring',\n"
        "        'dns.resolver',\n"
        "        'cryptography',\n"
        "        'cryptography.hazmat.primitives.ciphers.aead',\n"
        "        'PyQt6', 'PyQt6.QtWidgets', 'PyQt6.QtCore', 'PyQt6.QtGui',\n"
        "        'pyperclip', 'dotenv',\n"
        "    ],\n"
        "    hookspath=[],\n"
        "    runtime_hooks=[],\n"
        "    excludes=['tkinter', 'matplotlib', 'numpy', 'scipy'],\n"
        "    cipher=block_cipher,\n"
        "    noarchive=False,\n"
        ")\n"
        "pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)\n"
        "exe = EXE(\n"
        "    pyz, a.scripts, a.binaries, a.zipfiles, a.datas, [],\n"
        "    name='PPW-PasswordManager',\n"
        "    debug=False, strip=False, upx=True, console=False,\n"
        "    icon=" + icon_arg + ",\n"
        ")\n"
    )
    SPEC.write_text(spec_text, encoding="utf-8")
    print("[OK] ppw.spec written")


def build():
    print("-- Installing PyInstaller --")
    subprocess.check_call(
        [sys.executable, "-m", "pip", "install", "pyinstaller>=6.0", "-q"]
    )
    print("-- Running PyInstaller --")
    subprocess.check_call([
        sys.executable, "-m", "PyInstaller",
        "--clean",
        "--distpath", str(DIST),
        "--workpath", str(BUILD),
        str(SPEC),
    ])
    exe = DIST / "PPW-PasswordManager.exe"
    if not exe.exists():
        exe = DIST / "PPW-PasswordManager"
    if exe.exists():
        mb = round(exe.stat().st_size / 1_048_576, 1)
        print("[OK] Build complete: " + str(exe) + " (" + str(mb) + " MB)")
    else:
        print("[ERROR] EXE not found - check PyInstaller output above.")


if __name__ == "__main__":
    try:
        write_bundle()
        write_spec()
        build()
    finally:
        delete_bundle()

